name: Build

on: [push]

jobs:  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
    - uses: actions/checkout@v1
    - run: npm install
    - uses: actions/checkout@v1
    - run: npm run build --if-present
    - uses: actions/checkout@v1
    - run: npm test
